<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Xbim.Ifc" Version="6.0.445" />
        <PackageReference Include="Xbim.Ifc2x3" Version="6.0.445" />
        <PackageReference Include="Xbim.Ifc4" Version="6.0.445" />
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="Converter\**" />
        <Compile Remove="IFC\bin\**" />
        <Compile Remove="IFC\obj\**" />
        <Compile Remove="Start\bin\**" />
        <Compile Remove="Start\obj\**" />
        <Compile Remove="Test\**" />
        <Compile Remove="Start1\bin\**" />
        <Compile Remove="Start1\obj\**" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Remove="Converter\**" />
        <EmbeddedResource Remove="IFC\bin\**" />
        <EmbeddedResource Remove="IFC\obj\**" />
        <EmbeddedResource Remove="Start\bin\**" />
        <EmbeddedResource Remove="Start\obj\**" />
        <EmbeddedResource Remove="Test\**" />
        <EmbeddedResource Remove="Start1\bin\**" />
        <EmbeddedResource Remove="Start1\obj\**" />
    </ItemGroup>

    <ItemGroup>
        <None Remove="Converter\**" />
        <None Remove="IFC\bin\**" />
        <None Remove="IFC\obj\**" />
        <None Remove="Start\bin\**" />
        <None Remove="Start\obj\**" />
        <None Remove="Test\**" />
        <None Remove="Start1\bin\**" />
        <None Remove="Start1\obj\**" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Start1\" />
    </ItemGroup>

</Project>
