<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Configurations>Debug;Release;Parallel</Configurations>
        <Platforms>AnyCPU</Platforms>
        <LangVersion>default</LangVersion>
        <TargetFramework>net462</TargetFramework>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Parallel' ">
      <DefineConstants>TRACE;DEBUG</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Start\Start.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Xbim.Ifc" Version="6.0.493" />
      <PackageReference Include="Xbim.Ifc4" Version="6.0.493" />
      <PackageReference Include="Xbim.IO.MemoryModel" Version="6.0.493" />
    </ItemGroup>

</Project>
