<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Configurations>Debug;Release;Parallel</Configurations>
        <Platforms>AnyCPU</Platforms>
        <LangVersion>default</LangVersion>
        <TargetFramework>net462</TargetFramework>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Parallel' ">
        <DefineConstants>TRACE;DEBUG</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\IFC\IFC.csproj" />
        <ProjectReference Include="..\Start\Start.csproj" />
    </ItemGroup>

</Project>
