namespace IFC_Converter.Start.API;

public enum StartBaseRootFunctionKey
{
    PIPE_OUTSIDE_DIAMETER = 4,
    PIPE_MATERIAL_NAME = 7,
    PIPE_WALL_THICKNESS = 9,
    PIPE_MILL_TOLERANCE = 13,
    PIPE_CORROSION_ALLOWANCE = 14,
    PIPE_PRESSURE = 27,
    PIPE_TEST_PRESSURE = 29,
    PIPE_TEMPERATURE = 30,
    PIPE_UNIT_WEIGHT = 34,
    PIPE_INSULATION_UNIT_WEIGHT = 35,
    PIPE_PRODUCT_UNIT_WEIGHT = 36,
    PIPE_MANUFACTURING_TECHNOLOGY = 37,
    PIPE_LONGITUDINAL_WELD_JOINT_FACTOR = 38,
    PIPE_STRENGTH_FACTOR_OF_THE_TRAVERSE_WELD = 39,
    PIPE_ADDITIONAL_WEIGHT_LOAD = 61,
    PIPE_ADDITIONAL_NON_WEIGHT_LOAD_ON_THE_ABOVE_GROUND_SECTION_ALONG_X_AXIS = 64,
    PIPE_ADDITIONAL_NON_WEIGHT_LOAD_ON_THE_ABOVE_GROUND_SECTION_ALONG_Y_AXIS = 65,
    PIPE_ADDITIONAL_NON_WEIGHT_LOAD_ON_THE_ABOVE_GROUND_SECTION_ALONG_Z_AXIS = 66,
    PIPE_PROJECTION_ALONG_OX_AXIS = 128,
    PIPE_PROJECTION_ALONG_OY_AXIS = 129,
    PIPE_PROJECTION_ALONG_OZ_AXIS = 130,
    PIPE_NAME = 225,
    PIPE_PRODUCT_DENSITY = 263,
    
    NODE_ADDITIONAL_LOAD_FROM_WEIGHT = 61,
    NODE_NAME = 225,
    NODE_USE_NAME_FLAG = 226,
    NODE_DESCRIPTION = 227
}