namespace Start.API
{
    public enum StartConnectionTypeEnum
    {
        BUTT_WELD = 1,
        CONICAL_WALL_TRANSITION = 2,
        THREADED_CONNECTION_FLANGE = 3,
        FLANGE_FLAT_WELDED_WITH_DOUBLE_WELDING = 4,
        FLANGE_LOOSE_ON_WELD_RING = 5,
        CORNER_WELD_OR_SPLIT_WELD_FLANGE_UNTREATED = 6,
        CORNER_WELD_OR_SPLIT_WELD_FLANGE_MACHINED = 7,
        FLANGE_FLAT_WELDED_WITH_ONE_WELDING = 8,
    }
}