<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Configurations>Debug;Release;Parallel</Configurations>
        <Platforms>AnyCPU</Platforms>
        <LangVersion>default</LangVersion>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Parallel' ">
      <DefineConstants>TRACE;DEBUG</DefineConstants>
    </PropertyGroup>

</Project>
