//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STARTtoIFC {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("STARTtoIFC.LocalizationResource", typeof(LocalizationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string ExportButton_Text {
            get {
                return ResourceManager.GetString("ExportButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ExportWindow_Text {
            get {
                return ResourceManager.GetString("ExportWindow_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the correct file path.
        /// </summary>
        internal static string ExportWindowForm_ExportButton_Click_InvalidPath {
            get {
                return ResourceManager.GetString("ExportWindowForm_ExportButton_Click_InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path cannot be empty.
        /// </summary>
        internal static string ExportWindowForm_ExportButton_Click_NullPath {
            get {
                return ResourceManager.GetString("ExportWindowForm_ExportButton_Click_NullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to .ctp file.
        /// </summary>
        internal static string ExportWindowForm_InputFilepath_Label {
            get {
                return ResourceManager.GetString("ExportWindowForm_InputFilepath_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        internal static string ExportWindowForm_Log_Label {
            get {
                return ResourceManager.GetString("ExportWindowForm_Log_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to .ifc file.
        /// </summary>
        internal static string ExportWindowForm_OutputFilepath_Label {
            get {
                return ResourceManager.GetString("ExportWindowForm_OutputFilepath_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file for export.
        /// </summary>
        internal static string ExportWindowForm_selectOutputFilepathButton_Click_SelectFile {
            get {
                return ResourceManager.GetString("ExportWindowForm_selectOutputFilepathButton_Click_SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export cannot be done.
        /// </summary>
        internal static string ExportWindowForm_ShowExportResultWindow_Failure {
            get {
                return ResourceManager.GetString("ExportWindowForm_ShowExportResultWindow_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export done.
        /// </summary>
        internal static string ExportWindowForm_ShowExportResultWindow_Success {
            get {
                return ResourceManager.GetString("ExportWindowForm_ShowExportResultWindow_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to IFC.
        /// </summary>
        internal static string ExportWindowForm_Text {
            get {
                return ResourceManager.GetString("ExportWindowForm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MessageBox_Title_Error {
            get {
                return ResourceManager.GetString("MessageBox_Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string MessageBox_Title_Success {
            get {
                return ResourceManager.GetString("MessageBox_Title_Success", resourceCulture);
            }
        }
    }
}
